name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  composer:
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]
        include:
          - php-versions: 7.2
            env: COMPOSER_FLAGS="--prefer-lowest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
#          extensions: mbstring, simplexml, dom
#          coverage: xdebug #optional
      - name: Get composer cache directory
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}
      - name: Install dependencies
#        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

#  build:
#    strategy:
#      matrix:
##        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
#        operating-system: [ ubuntu-latest ]
#        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]
#
#    runs-on: ${{ matrix.operating-system }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup PHP, with composer and extensions
#        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
#        with:
#          php-version: ${{ matrix.php-versions }}
#          extensions: mbstring, simplexml, dom
#          coverage: xdebug #optional
#      - name: Get composer cache directory
#        id: composer-cache
#        uses: actions/cache@v2
#        with:
#          path: vendor
#          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-php-
#
##      - name: Validate composer.json and composer.lock
##        run: composer validate
##
#      - name: Cache Composer packages
#        id: composer-cache
#        uses: actions/cache@v2
#        with:
#          path: vendor
#          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-php-
#      - name: Install dependencies
#        if: steps.composer-cache.outputs.cache-hit != 'true'
#        run: composer install --prefer-dist --no-progress --no-suggest
#
#      - name: Php MD
#        if:
#        run: ./vendor/bin/phpmd src text ./ruleset.xml
#    - ./vendor/bin/phpcs
#
#      - name: Run Psalm
#        run: ./vendor/bin/psalm --output-format=github

#  psalm:
#    - name: Setup PHP
#      uses: shivammathur/setup-php@v2
#      with:
#        php-version: '7.4'
#        tools: psalm

